# Generated by Django 4.2.1 on 2023-05-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Username'),
        ),
    ]
