# Generated by Django 4.2.1 on 2023-05-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_employee_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.CharField(max_length=20, null=True, verbose_name='Designation'),
        ),
    ]
