# Generated by Django 4.2.1 on 2023-05-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_employee_empid'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='counter',
            field=models.IntegerField(default=0, verbose_name='Counter'),
        ),
    ]
