# Generated by Django 4.2.1 on 2023-05-19 12:38

from django.db import migrations, models
import time


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_alter_employee_login_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='login_counter',
            field=models.TimeField(default=time.time, null=True, verbose_name='counter'),
        ),
    ]
