# Generated by Django 4.2.1 on 2023-05-19 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_employee_login_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='login_counter',
        ),
    ]
