# Generated by Django 4.2.1 on 2023-05-20 10:35

from django.db import migrations, models
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_alter_employee_out_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_list', login.models.ListField(token=',')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='login_list',
            field=login.models.ListField(max_length=200, null=True, token=',', verbose_name='Login List'),
        ),
        migrations.AddField(
            model_name='employee',
            name='logout_list',
            field=models.CharField(max_length=200, null=True, verbose_name='Logout List'),
        ),
    ]
