# Generated by Django 4.2.1 on 2023-05-20 10:41

from django.db import migrations
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_alter_employee_login_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='logout_list',
            field=login.models.ListField(null=True, token=',', verbose_name='Logout List'),
        ),
    ]
