# Generated by Django 4.2.1 on 2023-05-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_alter_employee_logout_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='intime',
            field=models.CharField(max_length=200, null=True, verbose_name='Login Time'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='out_time',
            field=models.CharField(max_length=200, null=True, verbose_name='LogOut Time'),
        ),
    ]
