# Generated by Django 4.2.1 on 2023-05-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_alter_employee_out_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='intime',
            field=models.CharField(max_length=200, null=True, verbose_name='Current Login Time'),
        ),
    ]
