# Generated by Django 4.2.1 on 2023-05-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0022_alter_employee_counter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='counter',
            new_name='login_counter',
        ),
        migrations.AddField(
            model_name='employee',
            name='logout_counter',
            field=models.IntegerField(default=0, null=True, verbose_name='Logged Out'),
        ),
    ]
