# Generated by Django 4.2.1 on 2023-05-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0023_rename_counter_employee_login_counter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='login_counter',
            field=models.IntegerField(default=0, null=True, verbose_name='No. Of LogIn'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='logout_counter',
            field=models.IntegerField(default=0, null=True, verbose_name='No. Of Logout'),
        ),
    ]
