# Generated by Django 4.2.1 on 2023-05-22 05:02

from django.db import migrations
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0025_alter_employee_login_counter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='duration_list',
            field=login.models.ListField(null=True, token=',', verbose_name=' Login Duration List'),
        ),
    ]
