# Generated by Django 4.2.1 on 2023-05-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0027_employee_duration_time_alter_employee_duration_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(max_length=50, null=True, verbose_name='Depertment'),
        ),
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(max_length=50, null=True, verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='duration_time',
            field=models.CharField(max_length=200, null=True, verbose_name='Last Login Duration'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='listmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
